version: '3.3'

services:
  kong-database:
    container_name: some-kong-database
    image: cassandra:3
    restart: always
    volumes:
      - "/data/cassandra/data:/var/lib/cassandra"
    ports:
      - "9042:9042"

  kong:
    container_name: some-kong
    image: hhy5861/kong-rbac:13.1-1.0
    restart: always
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444